### ISSUE TITLE
How is it shown in Netbox UI?

### ISSUE THREAD

**Issue by joaolucasmacedo** [stfc/netbox-ip-status#1]
How is it shown in Netbox UI?
Is is not clear to me how to deploy it and how it will show in Netbox UI.

**Comment by willfurnell** [comment]
It shows in the Netbox UI as tags - it tags IP addresses.
It is a script that runs on a cron job - on any machine that has access to the Netbox API endpoint.

**Comment by joaolucasmacedo** [comment]
Hi. Thanks!
Actually I've figured out how to run it.
Also, it is necessary to change line 92 as bellow:
`                "address": ipy_address.strNormal(1) + prefix_mask,`
By
`                "address": ipy_address.strNormal(1) + '/' + prefix_mask,`
I dont know if it is something about Netbox version. I'm running Netbox 3.4.4 with Python 3.10.
I think that it would be nice to mention which version of Netbox it was designed for. I think some earlier release allowed to assign non existing tags, and now you have to create them before assignment.

**Comment by joaolucasmacedo** [comment]
Very nice script by the way. Very good idea.

**Comment by willfurnell** [comment]
Ah yes - I did fix that and not commit it!
