### ISSUE TITLE
Issues running IPv6

### ISSUE THREAD

**Issue by joaolucasmacedo** [stfc/netbox-ip-status#2]
Hi. I've used with some IPv6 prefixes and there are some issues that may be mentioned.
Besides it is not practical to scan IPv6 prefixes, looks like it also duplicates any IPv6 addresses found.

**Comment by willfurnell** [comment]
Hello,
Sorry I do not plan to support IPv6 with this - there will simply be too many addresses to scan to make it worthwhile.
