### ISSUE TITLE
AttributeError: module 'config' has no attribute 'PROD_HOSTNAM

### ISSUE THREAD

**Issue by jprodriguesc1** [stfc/netbox-ip-status#3]
Hello, first congratulations for the work, very good.

I have the following problem:

if socket.getfqdn() != config.PROD_HOSTNAME:
AttributeError: module 'config' has no attribute 'PROD_HOSTNAME'

If it's not too much trouble, could you help me?

**Comment by anaelsilvabh** [comment]
Hi,
you add a var PROD_HOSTNAME = "host name you server" in config.py

**Comment by willfurnell** [comment]
Sorry - @anaelsilvabh is correct - I will update the sample conf file with that
