### ISSUE TITLE
cant acess

### ISSUE THREAD

**Issue by netoxss** [stfc/netbox-ip-status#5]
Trying to run with http and gets this erro: The requested url: http://127.0.0.1/api/ipam/prefixes/?tag=ipstatus&limit=0 could not be found
And on https i get SSL verification error, can someone help me

**Comment by willfurnell** [comment]
That looks like it might be a problem with your configuration here (is localhost definitely your Netbox instance), and the SSL verification error may be because you're using a self signed rather than trusted certificate.
